services:
  - type: web
    name: millesime
    plan: free
    runtime: docker
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSL_MODE
        value: require
        sync: false
      - key: DB_SSL
        value: true
        sync: false
