services:
  - type: web
    name: millesime
    plan: free
    runtime: docker
    dockerCommand: ./run-app.sh
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
