server:
  port: ${SERVER_PORT:8081}

spring:
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
  datasource:
    platform: postgres
    url: ${DATABASE_URL:${DB_URL:jdbc:postgresql://localhost:5432/millesime}}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT:30000}
      idle-timeout: ${HIKARI_IDLE_TIMEOUT:600000}

  sql:
    init:
      mode: ${SQL_INIT_MODE:never}
      schema-locations: classpath:schema-postgresql.sql

  mail:
    host: ${MAIL_HOST:smtp.example.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:username}
    password: ${MAIL_PASSWORD:password}
    from: ${MAIL_FROM:no-reply@millesime.com.br}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: ${MAIL_HOST:smtp.example.com}

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
