server:
  port: 8081
  forwarded-headers-strategy: framework

spring:
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
  datasource:
    platform: postgres
    url: ${DATABASE_URL:${DB_URL:jdbc:postgresql://localhost:5432/millesime}}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2

  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgresql.sql
