server:
  port: ${PORT:8081}
  forwarded-headers-strategy: framework

spring:
  datasource:
    platform: postgres
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        sslmode: ${DB_SSL_MODE:require}
        ssl: ${DB_SSL:true}

  jpa:
    hibernate:
      ddl-auto: validate

  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgresql.sql

logging:
  level:
    root: INFO
    com.example.Millesime: DEBUG
