server:
  port: ${SERVER_PORT:8081}

spring:
  web:
    locale: pt_BR
    locale-resolver: fixed
    resources:
      chain:
        strategy:
          content:
            enabled: true

  sql:
    init:
      mode: ${SQL_INIT_MODE:never}
      schema-locations: classpath:schema-postgresql.sql

  mail:
    host: ${MAIL_HOST:smtp.example.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:username}
    password: ${MAIL_PASSWORD:password}
    from: ${MAIL_FROM:no-reply@millesime.com.br}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: ${MAIL_HOST:smtp.example.com}

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
