server:
  port: ${PORT:8081}

spring:
  datasource:
    platform: postgres
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  sql:
    init:
      mode: never

logging:
  level:
    root: INFO
    com.example.Millesime: DEBUG
